Docker 1
Otus-DevOps-2018-09/dmitriy-kharchenko_microservices pull request #1
Opened 2018-11-17 16:06 UTC by dmitriy-kharchenko

# Docker 1

В процессе выполнено:

- Запуска конейнера из образа Ubuntu
- Создание образа из контейнера
- Описание разницы вывода команд `docker inspect <u_container_id>` от `docker inspect <u_image_id>`
- Добавлена конфигурация Travis

2018-12-11 19:28 UTC, ujhgj requested changes

2018-12-11 19:28 UTC, ujhgj commented on docker-monolith/docker-1.log
> +Основным отличием вывода docker inspect <u_container_id> от docker inspect <u_image_id> является вывод информации о ресурсах, предоставляемых котнейнеру.
На основе вывода команд объясните чем отличается контейнер от образа

2018-12-13 07:48 UTC, dmitriy-kharchenko commented on docker-monolith/docker-1.log
> +Основным отличием вывода docker inspect <u_container_id> от docker inspect <u_image_id> является вывод информации о ресурсах, предоставляемых котнейнеру.
Образ - это слепок файловой системы, доступный только для чтения.

Контейнер - это процесс, запущенный из образа.

2018-12-14 15:38 UTC, ujhgj approved these changes

2018-12-15 10:13 UTC, merged